### ISSUE TITLE
Requirements for conda recipe?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#89]
I just tried to update my conda recipe to use the tagged release:

https://github.com/NOAA-ORR-ERD/orr-conda-recipes/tree/master/pyugrid

(yes, I should get this into this repo, but for now....)

I ended up having to add:
        - matplotlib
        - scipy
        - mock
        - nose

to the build dependency list -- which makes no sense you don't need those at build time (or netcdf4, actually) -- or do dependencies needed for tests go there too? but even then -- mock and nose???

Not a big deal, they are all in Anaconda, but it would be nice if this were cleaner.

**Comment by ocefpaf** [comment]
SciPy is [there](https://github.com/pyugrid/pyugrid/blob/master/conda-recipe/meta.yaml#L22). I left the optional matplotlib (and wxpython) out, but we can add them there...  However, I am against adding `mock` and `nose` to the recipe.  They are used only for testing and we do not run the tests\* while building the binaries.

\* One might argue that we should run the tests, but that is rarely done in a conda-recipe, to avoid longer builds.  Also, in theory, the released version was already tested.  And, because pyugrid is a pure python module, there is  virtually no difference across platforms to justify extra testing.

**Comment by ChrisBarker-NOAA** [comment]
I only added mock and nose because the build failed if I didn't.

But I have no idea why -- maybe because MPL requires them? I didn't take any time to investigate, but the goal is NOT to have them there.

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA are you using [this](https://github.com/pyugrid/pyugrid/tree/master/conda-recipe) recipe?  That one works here without any modification.

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I believe we can close this issue.

**Comment by ChrisBarker-NOAA** [comment]
what is the resolution? the recipe I hvae that's working:

https://github.com/NOAA-ORR-ERD/orr-conda-recipes/blob/master/pyugrid/meta.yaml

has the whoie pile of dependencies. I haven't tried it without them. But if you've got it building without them, then yes, let's close this issue.

**Comment by ocefpaf** [comment]
I don't have adim rights to close.

**Comment by ChrisBarker-NOAA** [comment]
hmm -- we should give you those. but for now, I'll close this.
